Models/Tuotteet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tuotteet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuotteet()
        {
            this.Tilausrivit = new HashSet<Tilausrivit>();
        }
    
        [Key]
        public int TuoteID { get; set; }
        public string Nimi { get; set; }
        public Nullable<decimal> Ahinta { get; set; }
        public byte[] Kuva { get; set; }
        public string ImageLink { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilausrivit> Tilausrivit { get; set; }
    }
}

Controllers/TuotteetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppTilausDB.Models;

namespace WebAppFirst.Controllers
{
    public class TuotteetController : Controller
    {
        // GET: Shippers
        TilausDBEntities db = new TilausDBEntities(); //Uusi ilmentymä tietokannasta nimellä db
        public ActionResult Index()
        {           
            //var tuotteet = db.Tuotteet;
            var tuotteet = db.Tuotteet.Include(s => s.Tilausrivit);
            return View(tuotteet.ToList());        }
        public ActionResult Index2()
        {
            //var tuotteet = db.Tuotteet;
            var tuotteet = db.Tuotteet.Include(s => s.Tilausrivit);

            return View(tuotteet.ToList());
        }
        [HttpGet]
        public ActionResult Edit(int? id) //parametri tutkitaan ja etsitään taulusta vastaavaa riviä. Jos vastaavuus löytyy, Näytetään Edit.cshtml sivu.
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("login", "home");
            }
            else
            {
                if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                Tuotteet tuotteet = db.Tuotteet.Find(id);
                if (tuotteet == null) return HttpNotFound(); //Jos vastaavuutta ei löydy, palautetaan sivua ei löydy virhe.
                return View(tuotteet);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult Edit([Bind(Include = "TuoteID,Nimi,Ahinta,ImageLink")] Tuotteet tuote) //Tämä metodi tallentaa muutokset kantaan ja paulauttaa sivun Tuotteets.cshtml
        {
            if (ModelState.IsValid)
            {
                db.Entry(tuote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tuote);
        }
        public ActionResult Create() //Tätä metodia kutsutaan listanäkymästä ja tämä metodi näyttää luontinäytön Create.cshtml
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("login", "home");
            }
            else
            {
                ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi");
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TuoteID,Nimi,Ahinta,ImageLink, Description")] Tuotteet tuote) //Tätä metodia kutsutaan luontinäytöltä, kun klikataan "Save".Metodi lisää uuden rivin tiedot kantaan.
        {
            if (ModelState.IsValid)
            {
                db.Tuotteet.Add(tuote);

                db.SaveChanges();
                ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi", tuote.TuoteID);

                return RedirectToAction("Index");
            }
            return View(tuote);
        }
        public ActionResult Delete(int? id)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("login", "home");
            }
            else
            {
                if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                Tuotteet tuote = db.Tuotteet.Find(id);
                if (tuote == null) return HttpNotFound();
                return View(tuote);
            }
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var tietue = new TilausDBEntities())
            {
                var x = (from y in tietue.Tilausrivit
                         where y.TuoteID == id
                         select y).FirstOrDefault();
                tietue.Tilausrivit.Remove(x);
                tietue.SaveChanges();
            }

            Tuotteet tuote = db.Tuotteet.Find(id);
            try
            {
                db.Tuotteet.Remove(tuote);
                

            }
            catch (Exception)
            {

                ViewBag.Message("Tuotetta ei voida poistaa, tuotteella on tilausrivejä.");
            }
                db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id) //parametri tutkitaan ja etsitään taulusta vastaavaa riviä. Jos vastaavuus löytyy, Näytetään Edit.cshtml sivu.
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Tuotteet tuote = db.Tuotteet.Find(id);
            if (tuote == null) return HttpNotFound(); //Jos vastaavuutta ei löydy, palautetaan sivua ei löydy virhe.
            return View(tuote);
        }
    }
}

Views/Tuotteet/Create.cshtml
@model WebAppTilausDB.Models.Tuotteet

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tuotteet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Tuotteet/Delete.cshtml
@model WebAppTilausDB.Models.Tuotteet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tuotteet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ahinta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ahinta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kuva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kuva)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Tuotteet/Details.cshtml
@model WebAppTilausDB.Models.Tuotteet

@{
    ViewBag.Title = "Tuotteen kuvaus";
}
<style>
    .container {
        position: relative;
        width: auto;
    }

    .image {
        display: block;
        width: auto;
        height: 200px;
    }

    .overlay {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        height: 100%;
        width: 100%;
        opacity: 0;
        transition: .5s ease;
        background-color: lightgrey;
    }

    .container:hover .overlay {
        opacity: 1;
    }

    .text {
        color: white;
        font-size: 20px;
        position: absolute;
        top: 50%;
        left: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        text-align: center;
    }
</style>
<h2>Details</h2>

<div>
    <h4>Tuotteet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ahinta)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Ahinta.Value.ToString("c"))*@
            @Model.Ahinta.Value.ToString("c")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kuva)
        </dt>

        <dd>
            <!--<a href="@Model.ImageLink"></a>--> @*Linkki Tuotteeseen ilman tekstiä.*@
            <div class="container">
                <img class="card-image-top" src="@Model.ImageLink" alt=@Model.ImageLink>
                <div class="overlay">
                    <div class="text"><a href="@Model.ImageLink">Click to see the source image</a></div>
                </div>
            </div>
            @*<img class="card-img-top" style="height: 200px; width: auto; display: block;" src=@Model.ImageLink alt="@Model.ImageLink">*@
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)

        </dt>
        <dd>@Html.DisplayFor(model => model.Description)</dd>

    </dl>
</div>
<p>
    @if (Session["UserName"] != null) { 

        @Html.ActionLink("Poista    ", "Delete", new { id = Model.TuoteID })
        @Html.ActionLink("Muokkaa  ", "Edit", new { id = Model.TuoteID })
        @Html.ActionLink("Takaisin listaan  ", "Index")
    }
    
</p>
    
<p>
    @if (Session["UserName"] == null) 
    { 

     @Html.ActionLink("Takaisin listaan", "Index")
    }
     
</p>
    
    

Views/Tuotteet/Edit.cshtml
@model WebAppTilausDB.Models.Tuotteet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tuotteet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TuoteID)

    <div class="form-group">
        @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kuva, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kuva, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Tuotteet/Index.cshtml
@model IEnumerable<WebAppTilausDB.Models.Tuotteet>
@{
    ViewBag.Title = "Index";
}

@section scripts
    {
    <script type="text/javascript">
        $(function () {
            $(".showProductId").click(function () {
                var productId = $(this).data("productid");
                alert(productId);

            });
        });
        $(function () {
            $("#poistaTuote").click(function () {
                var productId = $(this).data("productid");
                alert(productId);
            });
        });
    </script>
}

<div class=" container-fluid">
    <h2>Tuotekatalogi</h2>
@if (Session["UserName"] != null) //Tarkitetaan onko käyttäjä kirjautunut ja jos on, näytetään uuden tuotteen lisäys nappi.
{
    <div>
        <a class="btn btn-primary" href="/Tuotteet/Create" role="button">Lisää uusi Tuote</a>
    </div>
}
    <h5>Tuotteita @Model.Count() kappaletta</h5>

    <div class="row">

        @foreach (WebAppTilausDB.Models.Tuotteet prod in Model)
        {
            <div class="col-sm-3 col-md-6 col-lg-4">
                <div class=" card-deck">
                    <div class="card" style="width: 18rem; height:20rem;">
                        <a href="@Url.Action("Details", "Tuotteet", new { id=prod.TuoteID })" class="stretched-link"></a> @*Linkki Tuotteeseen ilman tekstiä.*@
                        <div>
                            <h3 class="card-header text-center" style="width:18rem;">
                                @prod.Nimi
                            </h3>
                            <div class="card-body text-center">
                                <img class="card-img-top" style="height:auto;width:auto;max-height:150px; max-width: 18rem; display: block;" src=@prod.ImageLink alt="@prod.ImageLink">
                                <br>
                                <div class="card-footer text-center" style="width:18rem;">

                                    <p>@prod.Ahinta.Value.ToString("c")</p>
                                    @*<li class="list-group-item">Unit price: @prod.UnitPrice</li>*@

                                </div>
                            </div>
                        </div>

                        @*<button class="btn btn-primary showProductId" data-productID="@prod.ProductID">Muokkaa</button>*@
                    </div>
                </div>
                <br>
            </div>
        }
    </div>
</div>
<script>
    function naytaValittuTuote(tuoteID) {
        alert(tuoteID);
    }
</script>

Views/Tuotteet/IndexVanha.cshtml
@model IEnumerable<WebAppTilausDB.Models.Tuotteet>

@{
    ViewBag.Title = "Index2";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ahinta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kuva)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ahinta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kuva)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TuoteID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TuoteID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TuoteID })
        </td>
    </tr>
}

</table>